### ISSUE TITLE
uncaughtException Error: spawn ccls ENOENT

### ISSUE THREAD

**Issue by javier-garcia-meteologica** [Maxattax97/coc-ccls#3]
### Observed behavior

```
// CocOpenLog in debug mode
// console.log() in coc-ccls->lib/serverContext.js->initClient->cp.spawn
2020-04-15T09:47:14.960 DEBUG (pid:738550) [extension-coc-ccls] - ["ccls",[],{"cwd":"file:///home/user/.vim/plugged/coc.nvim","env":{"PATH":"/usr/share/Modules/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin"}}]
2020-04-15T09:47:14.964 ERROR (pid:738550) [server] - uncaughtException Error: spawn ccls ENOENT    
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)    
    at onErrorNT (internal/child_process.js:415:16)    
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Even if I hardcode this, (note that PATH contains only one directory):

```
const child = cp.spawn('/usr/bin/ccls', args, { env: { PATH: '/usr/bin' } });
```

I get another bug:

```
2020-04-15T10:22:16.521 ERROR (pid:741649) [extensions] - Error: Language client is not ready yet    
    at LanguageClient.onNotification (/home/javier/.vim/plugged/coc.nvim/build/index.js:56763:19)    
    at new InactiveRegionsProvider (/home/javier/.config/coc/extensions/node_modules/coc-ccls/lib/inactiveRegions.js:25:21)    
    at ServerContext.<anonymous> (/home/javier/.config/coc/extensions/node_modules/coc-ccls/lib/serverContext.js:203:31)    
    at Generator.throw (<anonymous>)    
    at rejected (/home/javier/.config/coc/extensions/node_modules/coc-ccls/lib/serverContext.js:5:65)
```

### Expected behavior

Not to throw any error

### Steps to reproduce

Run nvim and activate coc-ccls extension

### System information

* ccls version: 0.20190823.5-1.fc31
* OS: Fedora 31
* Editor: nvim 0.4.3
* coc-nvim version: 0.0.78
* coc-ccls version: 0.0.5

```
$ which ccls
/usr/bin/ccls
```

**Comment by atoder** [comment]
I have the same error
